name: Regenerate Verified News Publishers List

on:
  push:
    paths:
      - "verified-news-publishers-list/Publishers/**"
      - "verified-news-publishers-list/create-lists.js"
  pull_request:
    paths:
      - "verified-news-publishers-list/Publishers/**"
      - "verified-news-publishers-list/create-lists.js"

jobs:
  generate-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run script to generate lists
        run: node verified-news-publishers-list/create-lists.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git status
          git add verified-news-publishers-list/verified-news-publishers-list.json verified-news-publishers-list/verified-news-publishers-list.pem
          git status
          git commit -m "Auto-generate verified news publishers lists"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
